version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - N8N_EDITOR_BASE_URL=http://91.206.179.11:5678
      - N8N_WEB_HOOK_URL=http://91.206.179.11:5678/
      - WEBHOOK_URL=http://91.206.179.11:5678/
      - N8N_EMAIL_MODE=false
      - N8N_PERSONALIZATION_ENABLED=false
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
    restart: always

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - langflow_data:/data
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    restart: always

volumes:
  n8n_data:
  langflow_data:
