version: '3.8'

services:
  traefik:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - /local-files:/files
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://n8n.aitech-lab.org/
      - N8N_SKIP_WEBHOOK_VALIDATION=true
      - EXECUTIONS_PROCESS=main
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_TEMPLATES_ENABLED=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.aitech-lab.org`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    restart: always

  langflow:
    image: langflowai/langflow:latest
    volumes:
      - langflow_data:/data
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langflow.rule=Host(`langflow.aitech-lab.org`)"
      - "traefik.http.services.langflow.loadbalancer.server.port=7860"
    restart: always

volumes:
  n8n_data:
  langflow_data:
