version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=http
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - NODE_ENV=production
    restart: always

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    volumes:
      - langflow_data:/data
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    restart: always

volumes:
  n8n_data:
  langflow_data:
